### PR TITLE
Add open letter from economists, update branding

### PR DESCRIPTION
**Pull request by craigcook**

### CODE REVIEW

**Review by maureenlholland — APPROVED** [review]
This all looks good to me. I don't see any other code references to the `/letter` url that is now `/ai-safety` 🧹 

1 minor concern is I don't think we should have any `package-lock.json` changes since there are no `package.json` updates

Might be good to get another person move familiar with the repo to confirm the redirects

**Review by pmac — APPROVED** [review]
💰

**Comment by maureenlholland** [comment]
one minor styling thing, should the numbered list be split out on separate lines?

Screenshot 2024-12-11 at 12 26 29 PM

**Comment by craigcook** [comment]
> one minor styling thing, should the numbered list be split out on separate lines?

I considered that but this is how it was formatted in the original document so I left it as-is.

**Comment by craigcook** [comment]
Updated to back out the package-lock changes (not sure how that even happened...)

**Review by maureenlholland — APPROVED** [review]
r++ merge at will!

**Pull request merged**
